apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name
  labels:
    app: myapp
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: nginx-pod
      labels:
        type: backend
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
