apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  labels:
    app: app-label
spec:
  containers:
    - name: nginx-controller
      image: nginx
      # args: ["10"] # If arguments are needed, use this
      # command: ["sleep"] # If a different command is needed, use this
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
