apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller-name
spec:
  replicas: 2
  template:
    metadata:
      name: pod-name
      labels:
        app: pod-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
